### ISSUE TITLE
Missing commas in example in Readme file

### ISSUE THREAD

**Issue by adriancorcoran** [hellosean1025/node-echarts#20]
## Version
Current - downloaded today

## What is expected
Install the node package and use the example script provided to get up and running. 

## What is going wrong
The sample script in the `readme.md` is missing commas and throws an error when run
![](https://screenshot.click/12-43-fmeze-nyybf.jpg)

## Step to reproduce
Follow the steps in the `readme.md`

## Environment
Node v10.11.0

**Comment by hellosean1025** [comment]
Fixed.
